### ISSUE TITLE
Other adaptation

### ISSUE THREAD

**Issue by aarizaq** [roVer-HM/simulte#1]
Sorry for contact using a issue.

I have been working in other adaptation for inet 4 and I have been more aggresive in my changes, I have changed most of the packets to Chunk type, if you want my files to check my approach I can send you.

There are several things that are not correct, one is the header compress, the other is the fragmentation, I am not sure if it works correctly.
Other thing that I am no sure is the header sizes. There are many headers with size 0, but if you use chunks, the header should have at least a byte.

**Comment by wischhof** [comment]
No problem - if you prefer contact by e-mail, you can contact me at lars.wischhof  [at]  hm.edu

Porting the packets to the new INET 4 packet types is still on our TODO list, that is why you observe the incorrect header sizes. The current version is an intermediate step for which our main interest was to be able to run simulte with INET 4 (since we require INET 4 for all our other models). If you have already ported the simulte packets to to Chunk types, we would be happy to include that - if you have a public repo sending us a link and/or a pull request would be great.
